import defaultTheme from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Manrope", ...defaultTheme.fontFamily.sans],
      },
      colors: {
        brand: {
          primary: "rgb(var(--brand-primary) / <alpha-value>)",
          info: "rgb(var(--brand-info) / <alpha-value>)",
          accent: "rgb(var(--brand-accent) / <alpha-value>)",
          warning: "rgb(var(--brand-warning) / <alpha-value>)",
          neutral: "rgb(var(--neutral-950) / <alpha-value>)",
        },
        neutral: {
          50: "rgb(var(--neutral-50) / <alpha-value>)",
          100: "rgb(var(--neutral-100) / <alpha-value>)",
          200: "rgb(var(--neutral-200) / <alpha-value>)",
          300: "rgb(var(--neutral-300) / <alpha-value>)",
          400: "rgb(var(--neutral-400) / <alpha-value>)",
          500: "rgb(var(--neutral-500) / <alpha-value>)",
          600: "rgb(var(--neutral-600) / <alpha-value>)",
          700: "rgb(var(--neutral-700) / <alpha-value>)",
          800: "rgb(var(--neutral-800) / <alpha-value>)",
          900: "rgb(var(--neutral-900) / <alpha-value>)",
          950: "rgb(var(--neutral-950) / <alpha-value>)",
        },
        gray: {
          50: "rgb(var(--neutral-50) / <alpha-value>)",
          100: "rgb(var(--neutral-100) / <alpha-value>)",
          200: "rgb(var(--neutral-200) / <alpha-value>)",
          300: "rgb(var(--neutral-300) / <alpha-value>)",
          400: "rgb(var(--neutral-400) / <alpha-value>)",
          500: "rgb(var(--neutral-500) / <alpha-value>)",
          600: "rgb(var(--neutral-600) / <alpha-value>)",
          700: "rgb(var(--neutral-700) / <alpha-value>)",
          800: "rgb(var(--neutral-800) / <alpha-value>)",
          900: "rgb(var(--neutral-900) / <alpha-value>)",
          950: "rgb(var(--neutral-950) / <alpha-value>)",
        },
        slate: {
          50: "rgb(var(--neutral-50) / <alpha-value>)",
          100: "rgb(var(--neutral-100) / <alpha-value>)",
          200: "rgb(var(--neutral-200) / <alpha-value>)",
          300: "rgb(var(--neutral-300) / <alpha-value>)",
          400: "rgb(var(--neutral-400) / <alpha-value>)",
          500: "rgb(var(--neutral-500) / <alpha-value>)",
          600: "rgb(var(--neutral-600) / <alpha-value>)",
          700: "rgb(var(--neutral-700) / <alpha-value>)",
          800: "rgb(var(--neutral-800) / <alpha-value>)",
          900: "rgb(var(--neutral-900) / <alpha-value>)",
          950: "rgb(var(--neutral-950) / <alpha-value>)",
        },
        blue: {
          50: "rgb(var(--brand-primary) / 0.08)",
          100: "rgb(var(--brand-primary) / 0.12)",
          200: "rgb(var(--brand-primary) / 0.2)",
          300: "rgb(var(--brand-primary) / 0.35)",
          400: "rgb(var(--brand-primary) / 0.55)",
          500: "rgb(var(--brand-primary) / 0.75)",
          600: "rgb(var(--brand-primary) / 0.9)",
          700: "rgb(var(--brand-primary) / 1)",
          800: "rgb(var(--brand-primary) / 1)",
          900: "rgb(var(--brand-primary) / 1)",
        },
        indigo: {
          50: "rgb(var(--brand-primary) / 0.08)",
          100: "rgb(var(--brand-primary) / 0.12)",
          200: "rgb(var(--brand-primary) / 0.2)",
          300: "rgb(var(--brand-primary) / 0.35)",
          400: "rgb(var(--brand-primary) / 0.55)",
          500: "rgb(var(--brand-primary) / 0.75)",
          600: "rgb(var(--brand-primary) / 0.9)",
          700: "rgb(var(--brand-primary) / 1)",
          800: "rgb(var(--brand-primary) / 1)",
          900: "rgb(var(--brand-primary) / 1)",
        },
        purple: {
          50: "rgb(var(--brand-info) / 0.08)",
          100: "rgb(var(--brand-info) / 0.12)",
          200: "rgb(var(--brand-info) / 0.2)",
          300: "rgb(var(--brand-info) / 0.35)",
          400: "rgb(var(--brand-info) / 0.55)",
          500: "rgb(var(--brand-info) / 0.75)",
          600: "rgb(var(--brand-info) / 0.9)",
          700: "rgb(var(--brand-info) / 1)",
          800: "rgb(var(--brand-info) / 1)",
          900: "rgb(var(--brand-info) / 1)",
        },
        orange: {
          50: "rgb(var(--brand-accent) / 0.08)",
          100: "rgb(var(--brand-accent) / 0.12)",
          200: "rgb(var(--brand-accent) / 0.2)",
          300: "rgb(var(--brand-accent) / 0.35)",
          400: "rgb(var(--brand-accent) / 0.55)",
          500: "rgb(var(--brand-accent) / 0.75)",
          600: "rgb(var(--brand-accent) / 0.9)",
          700: "rgb(var(--brand-accent) / 1)",
          800: "rgb(var(--brand-accent) / 1)",
          900: "rgb(var(--brand-accent) / 1)",
        },
        yellow: {
          50: "rgb(var(--brand-warning) / 0.08)",
          100: "rgb(var(--brand-warning) / 0.12)",
          200: "rgb(var(--brand-warning) / 0.2)",
          300: "rgb(var(--brand-warning) / 0.35)",
          400: "rgb(var(--brand-warning) / 0.55)",
          500: "rgb(var(--brand-warning) / 0.75)",
          600: "rgb(var(--brand-warning) / 0.9)",
          700: "rgb(var(--brand-warning) / 1)",
          800: "rgb(var(--brand-warning) / 1)",
          900: "rgb(var(--brand-warning) / 1)",
        },
        green: {
          50: "rgb(var(--brand-info) / 0.08)",
          100: "rgb(var(--brand-info) / 0.12)",
          200: "rgb(var(--brand-info) / 0.2)",
          300: "rgb(var(--brand-info) / 0.35)",
          400: "rgb(var(--brand-info) / 0.55)",
          500: "rgb(var(--brand-info) / 0.75)",
          600: "rgb(var(--brand-info) / 0.9)",
          700: "rgb(var(--brand-info) / 1)",
          800: "rgb(var(--brand-info) / 1)",
          900: "rgb(var(--brand-info) / 1)",
        },
        emerald: {
          50: "rgb(var(--brand-info) / 0.08)",
          100: "rgb(var(--brand-info) / 0.12)",
          200: "rgb(var(--brand-info) / 0.2)",
          300: "rgb(var(--brand-info) / 0.35)",
          400: "rgb(var(--brand-info) / 0.55)",
          500: "rgb(var(--brand-info) / 0.75)",
          600: "rgb(var(--brand-info) / 0.9)",
          700: "rgb(var(--brand-info) / 1)",
          800: "rgb(var(--brand-info) / 1)",
          900: "rgb(var(--brand-info) / 1)",
        },
        teal: {
          50: "rgb(var(--brand-info) / 0.08)",
          100: "rgb(var(--brand-info) / 0.12)",
          200: "rgb(var(--brand-info) / 0.2)",
          300: "rgb(var(--brand-info) / 0.35)",
          400: "rgb(var(--brand-info) / 0.55)",
          500: "rgb(var(--brand-info) / 0.75)",
          600: "rgb(var(--brand-info) / 0.9)",
          700: "rgb(var(--brand-info) / 1)",
          800: "rgb(var(--brand-info) / 1)",
          900: "rgb(var(--brand-info) / 1)",
        },
        red: {
          50: "rgb(var(--brand-accent) / 0.08)",
          100: "rgb(var(--brand-accent) / 0.12)",
          200: "rgb(var(--brand-accent) / 0.2)",
          300: "rgb(var(--brand-accent) / 0.35)",
          400: "rgb(var(--brand-accent) / 0.55)",
          500: "rgb(var(--brand-accent) / 0.75)",
          600: "rgb(var(--brand-accent) / 0.9)",
          700: "rgb(var(--brand-accent) / 1)",
          800: "rgb(var(--brand-accent) / 1)",
          900: "rgb(var(--brand-accent) / 1)",
        },
        pink: {
          50: "rgb(var(--brand-warning) / 0.08)",
          100: "rgb(var(--brand-warning) / 0.12)",
          200: "rgb(var(--brand-warning) / 0.2)",
          300: "rgb(var(--brand-warning) / 0.35)",
          400: "rgb(var(--brand-warning) / 0.55)",
          500: "rgb(var(--brand-warning) / 0.75)",
          600: "rgb(var(--brand-warning) / 0.9)",
          700: "rgb(var(--brand-warning) / 1)",
          800: "rgb(var(--brand-warning) / 1)",
          900: "rgb(var(--brand-warning) / 1)",
        },
        surface: {
          DEFAULT: "rgb(var(--surface) / <alpha-value>)",
          elevated: "rgb(var(--surface-elevated) / <alpha-value>)",
          muted: "rgb(var(--surface-muted) / <alpha-value>)",
        },
        text: {
          primary: "rgb(var(--text-primary) / <alpha-value>)",
          secondary: "rgb(var(--text-secondary) / <alpha-value>)",
          muted: "rgb(var(--text-muted) / <alpha-value>)",
          inverse: "rgb(var(--text-inverse) / <alpha-value>)",
        },
        border: {
          DEFAULT: "rgb(var(--border-color) / <alpha-value>)",
          subtle: "rgb(var(--border-subtle) / <alpha-value>)",
        },
        state: {
          success: "rgb(var(--success) / <alpha-value>)",
          danger: "rgb(var(--danger) / <alpha-value>)",
        },
        focus: "rgb(var(--focus-ring) / <alpha-value>)",
        "glass-bg": "rgb(var(--glass-bg) / <alpha-value>)",
        "glass-border": "rgb(var(--glass-border) / <alpha-value>)",
        "bg-sun": "rgb(var(--bg-gradient-sun) / <alpha-value>)",
        "bg-orange": "rgb(var(--bg-gradient-orange) / <alpha-value>)",
        "bg-sky": "rgb(var(--bg-gradient-sky) / <alpha-value>)",
        "bg-ocean": "rgb(var(--bg-gradient-ocean) / <alpha-value>)",
        "bg-ink": "rgb(var(--bg-gradient-ink) / <alpha-value>)",
      },
      boxShadow: {
        glass: "0 4px 20px rgb(var(--shadow-color) / 0.18)",
      },
      backdropBlur: {
        "glass": "12px",
      },
    },
  },
  plugins: [],
};
